
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router";



const AbuseManager = lazy(() => import("./pages/AbuseManager.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const KeywordManager = lazy(() => import("./pages/KeywordManager.tsx"));
const SystemConfig = lazy(() => import("./pages/SystemConfig.tsx"));
const Terms = lazy(() => import("./pages/Terms.tsx"));
const UsageManager = lazy(() => import("./pages/UsageManager.tsx"));
const WebBot = lazy(() => import("./pages/WebBot.tsx"));

export const userRoutes: RouteObject[] = [

	{ path: "/abuse-manager", element: <AbuseManager />},
	{ path: "/abusemanager", element: <AbuseManager />},
	{ path: "/", element: <App />},
	{ path: "/keyword-manager", element: <KeywordManager />},
	{ path: "/keywordmanager", element: <KeywordManager />},
	{ path: "/system-config", element: <SystemConfig />},
	{ path: "/systemconfig", element: <SystemConfig />},
	{ path: "/terms", element: <Terms />},
	{ path: "/usage-manager", element: <UsageManager />},
	{ path: "/usagemanager", element: <UsageManager />},
	{ path: "/web-bot", element: <WebBot />},
	{ path: "/webbot", element: <WebBot />},

];
